"""Occlusion repair by symmetry-group closure.

The task family: a structured grid has part of it blanked out with a marker
colour, and the answer is either the repaired grid or just the missing patch.

Method.  Collect a candidate set of cell-permutations (mirrors about every
half-integer axis, translations by every period, and -- for square grids --
the diagonals).  Keep a permutation only if it never contradicts an observed
cell and is supported by enough overlap.  Union-find over the surviving
permutations yields the orbit partition; because union-find closes under
composition, we recover the *whole group* generated by the accepted maps
without having to enumerate it.  Every orbit containing at least one observed
cell is then determined.
"""

from collections import Counter

from .. import grid as G
from ..task import Hyp

SOLVER = "symmetry"
MIN_SUPPORT = 0.30


def _h(n, f, c):
    return Hyp(n, f, c, SOLVER)


class _DSU:
    __slots__ = ("p",)

    def __init__(self, n):
        self.p = list(range(n))

    def find(self, x):
        p = self.p
        while p[x] != x:
            p[x] = p[p[x]]
            x = p[x]
        return x

    def union(self, a, b):
        ra, rb = self.find(a), self.find(b)
        if ra != rb:
            self.p[rb] = ra


_MAP_CACHE = {}


def _candidate_maps(h, w):
    """(name, fn) permutations to test.  Cached: the same grid geometry is
    asked for once per hypothesis variant, and building ~120 closures each
    time is pure overhead."""
    hit = _MAP_CACHE.get((h, w))
    if hit is not None:
        return hit
    maps = []
    for a in range(1, 2 * w - 2):
        maps.append(("mh%d" % a, (lambda a: lambda r, c: (r, a - c))(a)))
    for a in range(1, 2 * h - 2):
        maps.append(("mv%d" % a, (lambda a: lambda r, c: (a - r, c))(a)))
    for p in range(1, h):
        maps.append(("tr%d" % p, (lambda p: lambda r, c: (r + p, c))(p)))
    for q in range(1, w):
        maps.append(("tc%d" % q, (lambda q: lambda r, c: (r, c + q))(q)))
    # Diagonal translations.  A grid whose colour depends on (r+c) mod k or
    # (r-c) mod k is invariant under these and under nothing else in the list,
    # so without them every diagonally striped pattern is unrepairable.
    for p in range(1, min(h, w)):
        maps.append(("td%d" % p, (lambda p: lambda r, c: (r + p, c + p))(p)))
        maps.append(("ta%d" % p, (lambda p: lambda r, c: (r + p, c - p))(p)))
    if h == w:
        maps.append(("diag", lambda r, c: (c, r)))
        maps.append(("adiag", (lambda n: lambda r, c: (n - c, n - r))(h - 1)))
        maps.append(("rot90", (lambda n: lambda r, c: (c, n - r))(h - 1)))
    if len(_MAP_CACHE) > 64:
        _MAP_CACHE.clear()
    _MAP_CACHE[(h, w)] = maps
    return maps


_PART_CACHE = {}


def _partition(g, unknown, min_support, min_pairs):
    """Orbit partition and its values.  Memoised across hypothesis variants:
    strict, lax, patch and bounded all ask for exactly the same partition."""
    key = (g, unknown, min_support, min_pairs)
    hit = _PART_CACHE.get(key)
    if hit is not None:
        return hit
    res = _partition_build(g, unknown, min_support, min_pairs)
    if len(_PART_CACHE) > 96:
        _PART_CACHE.clear()
    _PART_CACHE[key] = res
    return res


def _repair(g, unknown, strict=True, min_support=MIN_SUPPORT, min_pairs=6):
    """Fill unknown cells from the symmetry group the observed cells witness.

    Maps are adopted *incrementally, best-supported first*, and a map is
    committed only if merging its orbits keeps every orbit single-valued.  An
    all-or-nothing version (adopt every non-contradicting map, then check) is
    far more fragile: one coincidental map -- a diagonal translation that
    happens to line up on three cells -- merges two genuine orbits and destroys
    an otherwise perfect reconstruction.  Here that map is simply declined.
    """
    return _repair_from(g, unknown, strict,
                        _partition(g, unknown, min_support, min_pairs))


def _partition_build(g, unknown, min_support, min_pairs):
    h, w = G.dims(g)
    n = h * w
    flat = [g[r][c] for r in range(h) for c in range(w)]
    known = [v != unknown for v in flat]
    nk = sum(known)
    if nk == n or nk < 3:
        return None

    cands = []
    for _name, f in _candidate_maps(h, w):
        pairs = 0
        bad = False
        links = []
        for r in range(h):
            base = r * w
            for c in range(w):
                t = f(r, c)
                if t is None:
                    continue
                tr, tc = t
                if not (0 <= tr < h and 0 <= tc < w):
                    continue
                i = base + c
                j = tr * w + tc
                if i >= j:
                    continue
                links.append((i, j))
                if known[i] and known[j]:
                    pairs += 1
                    if flat[i] != flat[j]:
                        bad = True
                        break
            if bad:
                break
        if bad or pairs < max(min_pairs, int(min_support * nk)):
            continue
        cands.append((pairs, links))
    if not cands:
        return None
    cands.sort(key=lambda t: -t[0])

    parent = list(range(n))

    def find(x, p=parent):
        while p[x] != x:
            p[x] = p[p[x]]
            x = p[x]
        return x

    vals = {}
    for i in range(n):
        if known[i]:
            vals[i] = flat[i]

    for _pairs, links in cands:
        trial = parent[:]

        def tfind(x, p=trial):
            while p[x] != x:
                p[x] = p[p[x]]
                x = p[x]
            return x

        tvals = dict(vals)
        ok = True
        for i, j in links:
            ri, rj = tfind(i), tfind(j)
            if ri == rj:
                continue
            vi, vj = tvals.get(ri), tvals.get(rj)
            if vi is not None and vj is not None and vi != vj:
                ok = False
                break
            trial[rj] = ri
            if vi is None and vj is not None:
                tvals[ri] = vj
            tvals.pop(rj, None)
        if ok:
            parent[:] = trial
            vals = tvals

    for i in range(n):
        find(i)
    return parent, vals, known, h, w


def _repair_from(g, unknown, strict, part):
    if part is None:
        return None
    parent, vals, known, h, w = part
    n = h * w
    out = [[g[r][c] for c in range(w)] for r in range(h)]
    filled = False
    for i in range(n):
        if not known[i]:
            v = vals.get(parent[i])
            if v is None:
                if strict:
                    return None
                continue
            out[i // w][i % w] = v
            filled = True
    if not filled and strict:
        return None
    return tuple(tuple(r) for r in out)


def _repair_bounded(g, unknown, strict=False, min_support=0.0, min_pairs=2,
                    grow=0):
    """Complete a pattern, but only inside the region it already occupies.

    Unbounded completion of a sparse motif tiles the whole grid, which is
    almost never what the task wants: the pattern is meant to be finished, not
    repeated forever.  Restricting the writes to the bounding box of the
    observed cells is the difference between "make this symmetric" and "wallpaper
    the canvas".
    """
    rep = _repair(g, unknown, strict, min_support, min_pairs)
    if rep is None:
        return None
    cells = [(r, c) for r, row in enumerate(g) for c, v in enumerate(row)
             if v != unknown]
    if not cells:
        return None
    h, w = G.dims(g)
    r0, c0, r1, c1 = G.bbox_of(cells)
    r0, c0 = max(0, r0 - grow), max(0, c0 - grow)
    r1, c1 = min(h - 1, r1 + grow), min(w - 1, c1 + grow)
    out = [list(row) for row in g]
    changed = False
    for r in range(r0, r1 + 1):
        for c in range(c0, c1 + 1):
            if g[r][c] == unknown and rep[r][c] != unknown:
                out[r][c] = rep[r][c]
                changed = True
    return tuple(tuple(r) for r in out) if changed else None


def _occluded_bbox(g, unknown):
    cells = [(r, c) for r, row in enumerate(g) for c, v in enumerate(row)
             if v == unknown]
    if not cells:
        return None
    return G.bbox_of(cells)


def _patch(g, unknown, strict=True, min_support=MIN_SUPPORT, min_pairs=6):
    rep = _repair(g, unknown, strict, min_support, min_pairs)
    if rep is None:
        return None
    bb = _occluded_bbox(g, unknown)
    if bb is None:
        return None
    return G.subgrid(rep, *bb)


# --------------------------------------------------------------------------

def _unknown_candidates(ctx):
    """Colours plausibly acting as the "hole" marker."""
    cands = Counter()
    if ctx.same_shape:
        for a, b in ctx.train:
            diff = set()
            for ra, rb in zip(a, b):
                for x, y in zip(ra, rb):
                    if x != y:
                        diff.add(x)
            if len(diff) == 1:
                cands[diff.pop()] += 1
    else:
        for a, b in ctx.train:
            bh, bw = G.dims(b)
            for c in G.palette(a):
                bb = _occluded_bbox(a, c)
                if bb and (bb[2] - bb[0] + 1, bb[3] - bb[1] + 1) == (bh, bw):
                    cands[c] += 1
    got = [c for c, n in cands.items() if n == len(ctx.train)]
    if got:
        return got
    return [c for c, _n in cands.most_common(3)]


def generate(ctx):
    res = []
    cands = _unknown_candidates(ctx)
    if not cands:
        # still worth trying the task background as a hole marker
        cands = [ctx.bg]
    for u in cands[:4]:
        for strict in (True, False):
            sfx = "" if strict else "_lax"
            res.append(_h("repair#%d%s" % (u, sfx),
                          (lambda u, s: lambda g: _repair(g, u, s))(u, strict),
                          3.0 if strict else 4.0))
            res.append(_h("patch#%d%s" % (u, sfx),
                          (lambda u, s: lambda g: _patch(g, u, s))(u, strict),
                          3.2 if strict else 4.2))
        res.append(_h("repair_loose#%d" % u,
                      (lambda u: lambda g: _repair(g, u, True, 0.12))(u), 5.0))
        res.append(_h("patch_loose#%d" % u,
                      (lambda u: lambda g: _patch(g, u, True))(u), 5.2))
        # Sparse mode: complete a pattern that is not yet symmetric, where only
        # a handful of cell pairs witness each axis.  A wrongly accepted axis
        # cannot survive validation on the training pairs, so the floor can be
        # low here in a way it must not be for occlusion repair.
        for strict in (False, True):
            res.append(_h("complete#%d%s" % (u, "" if strict else "_lax"),
                          (lambda u, s: lambda g: _repair(g, u, s, 0.0, 2))(u, strict),
                          5.5 if strict else 6.0))
        res.append(_h("complete_patch#%d" % u,
                      (lambda u: lambda g: _patch(g, u, True, 0.0, 2))(u), 6.0))
        for grow in (0, 1):
            res.append(_h("complete_box#%d+%d" % (u, grow),
                          (lambda u, gr: lambda g: _repair_bounded(g, u, False, 0.0, 2, gr))(u, grow),
                          4.8 + 0.3 * grow))
            res.append(_h("complete_box_s#%d+%d" % (u, grow),
                          (lambda u, gr: lambda g: _repair_bounded(g, u, False, 0.25, 4, gr))(u, grow),
                          5.0 + 0.3 * grow))
    return res
