#!/bin/sh
# Concatenate the engine sources into one browser bundle. The sources share a
# single lexical scope, so order matters and is fixed by the file names.
set -e
cd "$(dirname "$0")"
out=../c4-arc-engine.js
{
  echo "/* CELL4 ARC engine - browser bundle. Generated by c4-arc/build.sh."
  echo "   Sources live in c4-arc/src/. Do not edit this file by hand. */"
  echo "(function (root) {"
  echo "\"use strict\";"
  for f in src/*.js; do
    echo ""
    echo "/* ===== $f ===== */"
    cat "$f"
  done
  echo ""
  echo "root.C4ARCEngine = ENGINE;"
  echo "if (typeof module !== 'undefined' && module.exports) module.exports = ENGINE;"
  echo "})(typeof window !== 'undefined' ? window : globalThis);"
} > "$out"
wc -l "$out"
