/* Pack the public ARC corpus into one browser-loadable file.
 *
 * Grids are stored as rows of digits joined by "|" -- colours are 0-9, so one
 * character per cell is lossless and about a third the size of the JSON array
 * form. The unpacker in c4-arc.js reverses it.
 *
 *   node make-tasks.js [outfile]
 */

var fs = require("fs");
var path = require("path");

var ROOT = path.resolve(__dirname, "..");
var DATA = path.join(ROOT, "astron", "xyz", "data", "arc");
var OUT = process.argv[2] || path.join(ROOT, "c4-arc-tasks.js");

function packGrid(g) {
  var parts = [], r;
  for (r = 0; r < g.length; r++) parts.push(g[r].join(""));
  return parts.join("|");
}

function packPairs(pairs, withOutput) {
  var out = [], i;
  for (i = 0; i < pairs.length; i++) {
    if (withOutput) out.push(packGrid(pairs[i].input) + ">" + packGrid(pairs[i].output));
    else out.push(packGrid(pairs[i].input));
  }
  return out.join(";");
}

var files = fs.readdirSync(DATA).filter(function (f) { return /\.json$/.test(f); }).sort();
var rows = [];
files.forEach(function (f) {
  var d = JSON.parse(fs.readFileSync(path.join(DATA, f), "utf8"));
  var id = f.replace(/\.json$/, "");
  rows.push(JSON.stringify([id, packPairs(d.train, true), packPairs(d.test, true)]));
});

var body = "/* The public ARC-AGI-1 and ARC-AGI-2 task files, packed one row per\n" +
  " * task as [id, train, test]. Each pair is \"input>output\" and each grid is\n" +
  " * its rows of colour digits joined by \"|\". Generated by c4-arc/make-tasks.js.\n" +
  " */\n" +
  "(function (root) {\n\"use strict\";\nroot.C4ARCTasks = [\n" +
  rows.join(",\n") + "\n];\n" +
  "if (typeof module !== 'undefined' && module.exports) module.exports = root.C4ARCTasks;\n" +
  "})(typeof window !== 'undefined' ? window : globalThis);\n";

fs.writeFileSync(OUT, body);
console.log("wrote " + OUT + " (" + files.length + " tasks, " +
            Math.round(body.length / 1024) + " KB)");
