/* Wrap the trained planner weights as a browser-loadable file. */
var fs = require("fs"), path = require("path");
var ROOT = path.resolve(__dirname, "..");
var src = path.join(ROOT, "astron", "xyz", "policy", "arc_planner.json");
var out = process.argv[2] || path.join(ROOT, "c4-arc-policy.js");
var data = JSON.parse(fs.readFileSync(src, "utf8"));
var body = "/* Trained ARC planner: sparse log-linear weights over reasoning actions\n" +
  " * plus the signature -> family memory. Fitted offline by astron/xyz on solved\n" +
  " * tasks only; it reorders and rebudgets generators and can never make the\n" +
  " * engine accept a wrong answer. Generated by c4-arc/make-policy.js.\n" +
  " */\n(function (root) {\n\"use strict\";\nroot.C4ARCPlanner = " +
  JSON.stringify(data) + ";\n" +
  "if (typeof module !== 'undefined' && module.exports) module.exports = root.C4ARCPlanner;\n" +
  "})(typeof window !== 'undefined' ? window : globalThis);\n";
fs.writeFileSync(out, body);
console.log("wrote " + out + " (" + Math.round(body.length / 1024) + " KB)");
